### PR TITLE
Modify domain to saswata.cc from saswata.xyz

### PR DESCRIPTION
**Pull request by saswatasarkar13**
Just changing the domain, Everything else is the same.

Regards

### CODE REVIEW

**Comment by saswatasarkar13** [comment]
Resolves #130 

Regards

**Review by 2096779623 — CHANGES_REQUESTED** [review]
image
Add your previous domain name here.

**Comment by saswatasarkar13** [comment]
Added. Thanks for letting me know.

Regards

**Review by 2096779623 — APPROVED** [review]
Thanks!

**Pull request merged**
