### PR TITLE
mirrors: update chinese mainland mirrors

### PR DESCRIPTION
**Pull request by cherinyy**
`mirrors.aliyun.com`: fix x11 repo link

`mirrors.cqupt.edu.cn`: reducing redirects
`mirrors.ustc.edu.cn:` reducing redirects

`mirrors.dgut.edu.cn`: removed as unavailable
`mirrors.hit.edu.cn`: removed as unavailable
`mirrors.njupt.edu.cn`: removed as unavailable
`mirrors.scau.edu.cn`: removed as unavailable

### CODE REVIEW

**Comment by 2096779623** [comment]
Don't merge now, I need to investigate why these images are unavailable.

**Comment by 2096779623** [comment]
Thanks for PR,most of the reasons for being unavailable are that schools are on vacation and the server will be shut down to save power,so don’t remove them just yet(hit scau njupt).
dgut stopped serving last year.

**Comment by cherinyy** [comment]
> the reasons for being unavailable are that schools are on vacation and the server will be shut down to save power,so don’t remove them just yet(hit scau njupt)

This reasoning is unacceptable in my opinion and a highly available SLA should be required.

**Comment by 2096779623** [comment]
They also mirror other things, such as archlinux, so why don't the maintainers of archlinux remove it from the mirror list?

**Comment by 2096779623** [comment]
China's mirror sites currently have the largest number of mirror sites in the mirror list, so we don't need to worry about SLA.

**Comment by cherinyy** [comment]
> why don't the maintainers of archlinux remove it from the mirror list?

That's the point, the DGUT mirror removal for archlinux was submitted by me.

**Comment by 2096779623** [comment]
Because DGUT has stopped serving, there is no announcement from other mirror sites.

**Comment by cherinyy** [comment]
https://gitlab.archlinux.org/archlinux/rfcs/-/merge_requests/29

**Comment by 2096779623** [comment]
> https://gitlab.archlinux.org/archlinux/rfcs/-/merge_requests/29

The current solution is to reduce their `WEIGHT`, and then wait until the National Day to test again to see if there are any missing mirrors.

In addition, it is impossible for us to monitor the status of those mirrors in real time like archlinux, which will increase the load on their servers.
While there are many third-party websites that can be used to monitor these mirrors, I don't feel it's necessary. The user will always get a mirror available.

**Pull request closed without merging**
