### PR TITLE
mirrors: add mirror.autkin.net

### PR DESCRIPTION
**Pull request by andrey-utkin**
Hi, please kindly consider my mirror.

### CODE REVIEW

**Review by 2096779623 — APPROVED** [review]
Thanks!

**Comment by 2096779623** [comment]
Added to [wiki](https://github.com/termux/termux-packages/wiki/Mirrors#mirrors-by-andriy-utkin) .
BTW, what is the maximum bandwidth of your mirror?

**Comment by andrey-utkin** [comment]
2 MB/s.

**Comment by 2096779623** [comment]
> 2 MB/s.

We do not recommend building mirrors with such a small bandwidth, and I did not see speeds exceeding 2mb/s during testing.
 CC @Grimler91

**Comment by andrey-utkin** [comment]
2 MB/s is shared across all connections to the mirror.
You can withdraw my mirror from the list, no worries.

**Pull request merged**
