### PR TITLE
scripts/pkg.in: improved help message

### PR DESCRIPTION
**Pull request by Maxython**
Adding information about the `update` command and now the package format will change depending on the default package manager.

### CODE REVIEW

**Comment by agnostic-apollo** [comment]
I think using `from $TERMUX_APP_PACKAGE_MANAGER packages cache` would be better.

**Comment by Maxython** [comment]
> I think using `from $TERMUX_APP_PACKAGE_MANAGER packages cache` would be better.

Yes, it sounds better.

**Comment by Maxython** [comment]
@agnostic-apollo, I removed the word "packages" next to the package manager value. The thought remained but the explanation was reduced.

**Comment by agnostic-apollo** [comment]
Fine. Replace `package` in `update` info too with var.

**Comment by Maxython** [comment]
> Fine. Replace `package` in `update` info too with var.

Done

**Comment by agnostic-apollo** [comment]
Thanks.

**Pull request merged**
