### PR TITLE
add(termux-info): Output of variable `LD_LIBRARY_PATH` and `LD_PRELOAD`

### PR DESCRIPTION
**Pull request by 2096779623**
I think we'll need it at some point.

### CODE REVIEW

**Comment by truboxl** [comment]
I think include all the `env` variables also

**Comment by 2096779623** [comment]
> I think include all the `env` variables also

It maybe too long.

**Comment by truboxl** [comment]
ok ok
I think need to add other LD_* also like LD_PRELOAD, there maybe other LD_* I am not aware of
I am not sure LD_PRELOAD ald included or not...

**Comment by 2096779623** [comment]
> ok ok I think need to add other LD_* also like LD_PRELOAD, there maybe other LD_* I am not aware of I am not sure LD_PRELOAD ald included or not...

Other `LD_*` have not been used in the issues of termux-packages.

**Comment by agnostic-apollo** [comment]
You can check other variables at https://man7.org/linux/man-pages/man8/ld.so.8.html

To display them, I guess something like ` compgen -e "LD_" | while read v; do echo "${v}=${!v}"; done` could be used, but probably two variables should be sufficient.

```shell
LD Variables:
LD_LIBRARY_PATH=$LD_LIBRARY_PATH
LD_PRELOAD=$LD_PRELOAD
```

**Comment by agnostic-apollo** [comment]
Looks fine.

**Review by thunder-coding — APPROVED** [review]

**Pull request merged**
