### PR TITLE
mirrors: add mirrors.thebosshacker.in

### LINKED ISSUE #87: Request to Add New Termux Mirror: France
Hello,

I would like to request the addition of a new Termux mirror with the following specifications:

- **Location:** France
- **Bandwidth:** 1 Gbps
- **IP Support:** IPv4 only
- **Protocols:** HTTP,HTTPS 
- **Update Frequency:** Every 6 hours

`https://mirrors.thebosshacker.in/termux`

If any additional details are required, please let me know. I am happy to provide further information.

Thank you for your attention to this request.

Best regards,  
**Tbh**

### PR DESCRIPTION
**Pull request by 2096779623**
Close #87 .

### CODE REVIEW

**Comment by agnostic-apollo** [comment]
Don't think a mirror owned by such an user/org should be added.

https://github.com/thebosshacker-in/BossAdv

**Review by TomJo2000 — CHANGES_REQUESTED** [review]
I'd also like to veto this mirror on the basis of violating (packaging) guidelines.

**Comment by TbhV2** [comment]
Hi, 👋 i expected 
But this was promoting a person to lie and discovering a skill and knowledges, if can't anybody can expose or truth can't tell ?, this was absolutely promoting to such more activities, and others are ? Why trusting ? Termux lack of security ? simply if need person or hacker something like activity come on - fake accounts such ! Simply accept! So there is anybody didn't know who's and the past of contributors! And Etc Anything this all in the world ,all services same !, I just telling this happened the whole world and this was closing 😕 I know ; 

is only a domain issue ? I know but if accept change domain i directly asking !

**Comment by agnostic-apollo** [comment]
It's a domain issue too, but you are also maintaining phishing repositories and likely using such attacks, we do not allow such activities as per our community and packaging policies and do not want to be associated such users or organizations.

- https://github.com/termux/termux-community/blob/site/site/pages/en/rules/hacking.md

**Comment by thebosshacker-in** [comment]
I deleted both repository i didn't and i already quited from hacking but nick name Tbh thats I love it , excluding boss if accept ? tbh and based names or excluding blacklisted related names ? You will accept ? and i think you will see last commit 2 year's ago and that's learning curve

**Pull request closed without merging**
